apiVersion: v1
kind: Service
metadata:
  name: wannago-frontend
  namespace: wannago
spec:
  type: ExternalName
  externalName: host.k3s.internal
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wannago-api
  namespace: wannago
spec:
  type: ExternalName
  externalName: host.k3s.internal
  ports:
    - port: 3010
      targetPort: 3010
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wannago-host
  namespace: wannago
subsets:
  - addresses:
      - ip: 10.0.0.201  # IP de l'hôte dans le réseau k8s
    ports:
      - port: 80
        name: http
      - port: 3010
        name: api
---
apiVersion: v1
kind: Service
metadata:
  name: wannago-host
  namespace: wannago
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 3010
      targetPort: 3010
      name: api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wannago-ingress
  namespace: wannago
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - wannago.dorianlovichi.com
      secretName: wannago-tls
  rules:
    - host: wannago.dorianlovichi.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wannago-host
                port:
                  number: 3010
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wannago-host
                port:
                  number: 80
